webtalk_init -webtalk_dir C:/Users/rinel/Desktop/computer_architecture_project/hdmi_out_test/hdmi_out_test.sim/sim_1/behav/xsim/xsim.dir/hdmi_controller_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 16 12:24:00 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d078fa144fd657ff8c1fe93492852719" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f1f62cc2544041c48d0b8cd9c9c48e81" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "5094617875 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "127.53_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14300_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2187701047 -regid "" -xml C:/Users/rinel/Desktop/computer_architecture_project/hdmi_out_test/hdmi_out_test.sim/sim_1/behav/xsim/xsim.dir/hdmi_controller_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/rinel/Desktop/computer_architecture_project/hdmi_out_test/hdmi_out_test.sim/sim_1/behav/xsim/xsim.dir/hdmi_controller_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/rinel/Desktop/computer_architecture_project/hdmi_out_test/hdmi_out_test.sim/sim_1/behav/xsim/xsim.dir/hdmi_controller_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
