set_property SRC_FILE_INFO {cfile:C:/Users/rinel/Desktop/computer_architecture_project/test_clock/test_clock.srcs/constrs_1/imports/docs/PYNQ-Z1_C.xdc rfile:../../../test_clock.srcs/constrs_1/imports/docs/PYNQ-Z1_C.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports clk]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports led]
