# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/consts.xdc

# IP: ip/clk_wiz_poorly/clk_wiz_poorly.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_poorly || ORIG_REF_NAME==clk_wiz_poorly} -quiet] -quiet

# IP: ip/clk_wiz_precise/clk_wiz_precise.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_precise || ORIG_REF_NAME==clk_wiz_precise} -quiet] -quiet

# IP: ip/clk_wiz_pre/clk_wiz_pre.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_pre || ORIG_REF_NAME==clk_wiz_pre} -quiet] -quiet
