# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/condivisione/BACKUPS/backup_polito/computer_architecture/project/dvi_edge_detector/dvi_edge_detector.srcs/sources_1/ip/block_ram/block_ram.xci
# IP: The module: 'block_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/condivisione/BACKUPS/backup_polito/computer_architecture/project/dvi_edge_detector/dvi_edge_detector.srcs/sources_1/ip/block_ram/block_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /mnt/condivisione/BACKUPS/backup_polito/computer_architecture/project/dvi_edge_detector/dvi_edge_detector.srcs/sources_1/ip/block_ram/block_ram.xci
# IP: The module: 'block_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/condivisione/BACKUPS/backup_polito/computer_architecture/project/dvi_edge_detector/dvi_edge_detector.srcs/sources_1/ip/block_ram/block_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
